version: '3'

services:

  mysql-development:
    image: mysql:8.0.17
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=inventory_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    ports:
      - "3306:3306"
  
  app:
    image: app_backend
    restart: always
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/app
    entrypoint: ["python", "run.py"]